from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (HomePageView,
                    SignUpView,
                    MovieListView, 
                    MovieDetailView, 
                    MovieUpdateView,
                    MovieDeleteView, 
                    MovieCreateView,
                    CommentDeleteView,
                    CommentUpdateView,
                    MovieLikeView,
                    MovieSearchView,
                    PopularMovieListView,
                    ComedyMovieListView,
                    SportMovieListView,
                    ActionMovieListView,
                    AnimationMovieListView,
                    BiographyMovieListView,
                    DocumentaryMovieListView,
                    DramaMovieListView,
                    FantasyMovieListView,
                    HorrorMovieListView,
                    MusicalMovieListView,
                    MysteryMovieListView,
                    ScienceFictionMovieListView,
                    ThrillerMovieListView,
                    RomanceMovieListView,
                    WarMovieListView,
                    WesternMovieListView,
                    movie_list
                    )
urlpatterns = [

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('movies/kinopoisk', movie_list, name='movie_kinopoisk_list'),
    path("home/", HomePageView.as_view(), name="home"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("<int:pk>/", MovieDetailView.as_view(),
        name="movie_detail"),
    path("<int:pk>/edit/", MovieUpdateView.as_view(),
        name="movie_edit"),
    path("<int:pk>/delete/", MovieDeleteView.as_view(),
        name="movie_delete"),
    path("new/", MovieCreateView.as_view(), name="movie_new"),
    path("", MovieListView.as_view(),
        name="movie_list"),
    path("comedy/", ComedyMovieListView.as_view(),
        name="comedy_movie_list"),
    path("sport/", SportMovieListView.as_view(),
        name="sport_movie_list"),
    path("action/", ActionMovieListView.as_view(),
        name="action_movie_list"), 
    path("animation/", AnimationMovieListView.as_view(),
        name="animation_movie_list"), 
    path("biography/", BiographyMovieListView.as_view(),
        name="biography_movie_list"), 
    path("documentary/", DocumentaryMovieListView.as_view(),
        name="documentary_movie_list"), 
    path("drama/", DramaMovieListView.as_view(),
        name="drama_movie_list"), 
    path("fantasy/", FantasyMovieListView.as_view(),
        name="fantasy_movie_list"), 
    path("horror/", HorrorMovieListView.as_view(),
        name="horror_movie_list"), 
    path("musical/", MusicalMovieListView.as_view(),
        name="musical_movie_list"), 
    path("mystery/",  MysteryMovieListView.as_view(),
        name="mystery_movie_list"), 
    path("sciencefiction/", ScienceFictionMovieListView.as_view(),
        name="science_movie_list"), 
    path("thriller/", ThrillerMovieListView.as_view(),
        name="thriller_movie_list"), 
    path("romance/", RomanceMovieListView.as_view(),
        name="romance_movie_list"), 
    path("war/", WarMovieListView.as_view(),
        name="war_movie_list"), 
    path("western/", WesternMovieListView.as_view(),
        name="western_movie_list"),            
    path('movie/<int:pk>/like/', MovieLikeView.as_view(), name='like_movie'),
    path("<int:pk>/delete/comment/", CommentDeleteView.as_view(),
        name="comment_delete"),
    path("<int:pk>/edit/comment/", CommentUpdateView.as_view(),
        name="comment_edit"),
    path('search/', MovieSearchView.as_view(), name='movie_search'),
    path('popular/', PopularMovieListView.as_view(), name='popular_movie_list'),
    ]

