# Generated by Django 4.2.6 on 2023-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
